- name: Wait for BIG-IP to boot up completely
  wait_for:
    host: "{{ ansible_host }}"
    port: 8443
    state: present

- name: Change BIG-IP F5 mgmt password
  bigip_command:
    provider:
      ssh_keyfile: "{{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
      transport: cli
      user: admin
      server: "{{ ansible_host }}"
    commands: "modify auth user admin password {{admin_password}}"

- set_fact:
     provider_info:
      user: admin
      password: "{{admin_password}}"
      server: "{{ ansible_host }}"
      server_port: "8443"
      validate_certs: "False"

- name: Wait for BIG-IP to boot up completely
  bigip_wait:
    provider: "{{provider_info}}"
    
- name: Grab the AS3 version from the files directory
  shell: ls -Art {{ playbook_dir }}/roles/f5_setup/files/*.rpm | tail -n 1 | rev | cut -d/ -f 1 | rev
  register: ls_output

- set_fact:
   as3_rpm: "{{ls_output.stdout}}"

# The bigip_iapplx_package requires rpm installed, on macOS use brew rather than pip or it won't work
#- name: Install AS3
#  bigip_iapplx_package:
#    package: "{{playbook_dir}}/roles/f5_setup/files/{{as3_rpm}}"
#    provider: "{{provider_info}}"